#!/bin/bash

sushdir=${1:-~/GIT/rusty_bash}
testdir=${2:-~/GIT/bash_for_sush_test/tests}

( cd $sushdir && cargo build) || exit 1 

export SUSH_COMPAT_TEST_MODE=1
export THIS_SH="${sushdir}/target/debug/sush"

cd $testdir || exit 1

for t in $(echo run-*) ; do
	[[ "$t" == "run-all" ]] && continue;
	[[ "$t" == "run-minimal" ]] && continue;
	echo $t $(BASH_TSTOUT=/tmp/$$-$t bash $t | wc -l) 2> /dev/null &
done
