#!/bin/bash -xv

#ulimit -v 10000000
#ulimit -m 10000000

dir=$(dirname $0)

export SUSH_COMPAT_TEST_MODE=1
export TMPDIR=/tmp
export PATH=$PATH:$HOME/GIT/bash_for_sush_test/tests
export LC_ALL=en_US.utf8

timeout 115 $dir/bash_genuine_test_sub > /tmp/$$-result &

sleep 120

gawk '{a[$1]=$2}END{for(k in a)print k, a[k]}' $dir/bash_genuine_test_list /tmp/$$-result 
