#!/bin/bash

#ulimit -v 10000000
#ulimit -m 10000000

HOME=~

sushdir=~/GIT/rusty_bash
testdir=~/GIT/bash_for_sush_test/tests
export PATH=$PATH:$HOME/GIT/bash_for_sush_test/tests
export SUSH_COMPAT_TEST_MODE=1
export TMPDIR=/tmp

( cd $sushdir && cargo build) || exit 1 

cd $testdir

export THIS_SH="${sushdir}/target/debug/sush"

cd $testdir || exit 1

BASH_TSTOUT=/tmp/$$-$t bash $1
