#!/usr/local/bin/bash -xv

cat > /tmp/$$-result

echo OK:  $(gawk '$2==0' /tmp/$$-result | wc -l)
echo NG: $(gawk '$2!=0' /tmp/$$-result | wc -l)
echo DNF: $(gawk '$2=="DNF"' /tmp/$$-result | wc -l)
echo DIFF_LINES: $(gawk '$2!="DNF"{a+=$2}END{print a}' /tmp/$$-result)
