#!/bin/bash -xv

gdate=$(gdate "+%Y%m%d")

#ulimit -v 10000000
#ulimit -m 10000000

echo $gdate
./bash_genuine_test | tee $gdate.result | bash ./summary | tee $gdate.summary
#./graph

cat $gdate.summary
